# Generated by Django 4.2.5 on 2023-10-23 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='typee',
            field=models.CharField(max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_account',
            field=models.CharField(max_length=7, verbose_name='Pay Account'),
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=20, verbose_name='Transaction')),
                ('positive_negative', models.CharField(max_length=1, verbose_name='Positeve or Negative')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Value')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('number', models.CharField(blank=True, max_length=7, unique=True, verbose_name='Number')),
                ('date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_historic', to='api.account')),
            ],
        ),
    ]
