# Generated by Django 4.2.5 on 2023-10-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
