# Generated by Django 4.2.5 on 2023-09-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_phone_area_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anddress',
            new_name='Address',
        ),
    ]
