# Generated by Django 4.2.5 on 2023-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customusuario_name_alter_account_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='number',
            field=models.CharField(max_length=7, verbose_name='Number'),
        ),
    ]
