# Generated by Django 4.2.5 on 2023-10-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_number_alter_legalperson_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Value')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_card', to='api.card')),
            ],
        ),
    ]
