# Generated by Django 4.2.5 on 2023-09-22 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_anddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_legalPerson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_naturalPerson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phone',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_phones', to=settings.AUTH_USER_MODEL),
        ),
    ]
