# Generated by Django 4.2.5 on 2023-09-25 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_address_client_alter_legalperson_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=4, verbose_name='Agency')),
                ('number', models.CharField(max_length=7, unique=True, verbose_name='Number')),
                ('typee', models.CharField(max_length=10, verbose_name='Type')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='CreditLimit')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='Number')),
                ('expiration_date', models.DateField()),
                ('verification_number', models.CharField(max_length=3, verbose_name='Verification Number')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_card', to='api.account')),
            ],
        ),
    ]
