# Generated by Django 4.2.5 on 2023-10-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_type_transaction_typee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='typee',
            new_name='transaction_type',
        ),
    ]
