# Generated by Django 4.2.5 on 2023-09-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_account_caard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caard',
            new_name='Card',
        ),
    ]
