# Generated by Django 4.2.5 on 2023-09-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_caard_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='photograph',
            field=models.CharField(blank=True, max_length=400, verbose_name='Photograph'),
        ),
    ]
